### ISSUE TITLE
Geht das einfacher?

### ISSUE THREAD

**Issue by derech1e** [xXNicksdaXx/selfradio-backend#1]
Hey hab gerade gesehen das du die letzen Tage ja etwas gemacht hast. 😄 🚀
Dein Quellcode sieht soweit echt super aus! Respekt.

Einlass ist mir aufgefallen:
https://github.com/xXNicksdaXx/selfradio-backend/blob/a1eddd9c86b9fb0d7e230fadf0ff7f3cc0b621ff/src/song/song.controller.ts#L93

Deine Bedingung wird an der Stelle immer `true` sein. Ich vermute das das letze `&&` ein `==` sein sollte.

Daher denke ich das kann man so vereinfachen:
```javascript
 if(!title && !artist && !album) { 
```

**Comment by xXNicksdaXx** [comment]
Ah, das ist natürlich deutlich besser! Werde ich umsetzen, danke dir :)
